### ISSUE TITLE
Version requirements for individual functions - how to enforce?

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/effective-fiesta#1]
Using the `plot_vars` function as directly sourced from GitHub in the OTN 2024 ECR workshop, we discovered a semi-obscured error that we determined had to do with patchwork < 1.2.0, as described here: https://github.com/tidyverse/ggplot2/issues/5612 

Maybe this is just informational... Do we even have a way to enforce minimum versions if we are using `effective-fiesta` functions in a cherry-pick fashion?

**Comment by hugomflavio** [comment]
I think it should be possible to add a version check within the function itself? I'll have a look at that.
